### PR TITLE
Revert "Rebuild for pypy"

### PR DESCRIPTION
**Pull request by rluria14**
Reverts conda-forge/localstack-feedstock#14

### CODE REVIEW

**Comment by oblute** [comment]
@conda-forge-admin please restart ci

**Comment by oblute** [comment]
@conda-forge/core any idea why the windows builds are failing at the conda build step?

**Comment by jakirkham** [comment]
Please make sure to use a fork when making PRs

https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests

**Comment by oblute** [comment]
@jakirkham this was a automatically generated PR to revert a accidental merge for a autobot pypy rebuild...

**Comment by jakirkham** [comment]
The issue is branches on the feedstock will automatically deploy when they pass

In any event, I’m not sure how one reverts a bot PR. The die may already be cast (so to speak)

Are you just wanting to disable the PyPy builds? Or what is the goal here?

**Comment by oblute** [comment]
@jakirkham The PR to rebuild for PyPy was merged accidentally previously on this feedstock, and the maintainer above opened a PR to revert that merge, as it was failing on Linux and Osx due to a boto3 issue.  The question is, yes, how can we disable the PyPy builds now, as their existence is now causing all further updates to this feedstock to fail?

**Comment by jakirkham** [comment]
Would add this to the `meta.yaml`.

`yaml
build:
  skip: True         # [python_impl == 'pypy']
```

ref: https://conda-forge.org/docs/maintainer/knowledge_base.html#pypy-builds

**Comment by oblute** [comment]
@jakirkham yep, thanks! fixed in https://github.com/conda-forge/localstack-feedstock/pull/20 earlier

**Pull request closed without merging**
